repos:
  - repo: local
    hooks:
      - id: freeze-uv-requirements
        name: Freeze uv requirements
        entry: bash scripts/freeze_and_add.sh
        language: system
        types: [python]
